---
title: "Sunburst"

spell:
  schools:
    - name:        "Evocation"
      subschools:  []
      descriptors: ["Light"]
  classes:
    - name:  "Druid"
      abbr:  "Drd"
      level: 8
    - name:  "Sorcerer/Wizard"
      abbr:  "Sor/Wiz"
      level: 8
  domains:
    - name:  "Sun"
      abbr:  "Sun"
      level: 8
  components:         [V, S, M/DF]
  castingTime:        "1 standard action"
  range:              "Long (400 ft. + 40 ft./level)"
  area:               "80-ft.-radius burst"
  duration:           "Instantaneous"
  savingThrow:        "Reflex partial; see text"
  spellResistance:    "Yes"
  materialComponents: ["A piece of sunstone and a naked flame."]
  description:        |
    Sunburst causes a globe of searing radiance to explode silently from a point you select. All creatures in the globe are blinded and take 6d6 points of damage. A creature to which sunlight is harmful or unnatural takes double damage. A successful Reflex save negates the blindness and reduces the damage by half.

    An undead creature caught within the globe takes 1d6 points of damage per caster level (maximum 25d6), or half damage if a Reflex save is successful. In addition, the burst results in the destruction of any undead creature specifically harmed by bright light if it fail its save.

    The ultraviolet light generated by the spell deals damage to fungi, mold, oozes, and slimes just as if they were undead creatures.

    Sunburst dispels any darkness spells of lower than 9th level within its area.
---